name: NeoPvp
main: me.neoblade298.neopvp.NeoPvp
author: [Neoblade298]
depend: [NeoCore]
softdepend: [MythicMobs, Multiverse-Core]
version: 1.0
api-version: 1.16
commands:
   pvp:
      usage: /pvp
   war:
      usage: /war
   adminwar:
      usage: /adminwar
      aliases: awar
   adminpvp:
      usage: /adminpvp
      aliases: apvp